### ISSUE TITLE
Adição como contribuidor e outras coisas

### ISSUE THREAD

**Issue by marcoonroad** [rt3norio/psw2017#1]
Venho aqui pedir pra me adicionar como contribuidor do projeto. Seria legal também mudar o nome do projeto pra algo como Coruja-2.0, RESTful-Coruja, etc. O atual nome do projeto lembra mais um nome de um grupo. E falando nisso, seria ideal criar uma "Organização" aqui no GitHub e mover este projeto pra tal Organização. O atual nome do projeto fica muito bom também sendo o nome da própria Organização. O conselho pra criar uma organização é devido à estas terem ferramentas melhores para manusear contribuições e dar privilégios à certos contribuidores.

**Comment by marcoonroad** [comment]
Se precisar de ajuda, é só comentar nessa thread/discussão assumindo forma de issue.

**Comment by jtricolor16** [comment]
Me adiciona aí, Rodrigo

**Comment by marcoonroad** [comment]
^ @rt3norio, é como marcamos no GitHub. Talvez ajude...

**Comment by marcoonroad** [comment]
@jtricolor16 entra aqui https://github.com/orgs/faeterj-psw-2017 ou cheque seu email
